CREATE TABLE IF NOT EXISTS comments_books (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL,
    book_id BIGINT NOT NULL,
    text VARCHAR NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
