// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package pg

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CommentsBook struct {
	ID        int64
	UserID    int64
	BookID    int64
	Text      string
	CreatedAt pgtype.Timestamptz
}

type Complaint struct {
	ID        int64
	UserID    int64
	BookID    int64
	Text      string
	CreatedAt pgtype.Timestamptz
}

type Subscription struct {
	ID           int64
	SubscriberID int64
	SubscribeeID int64
}

type UserFavoriteBook struct {
	ID        int64
	UserID    int64
	BookID    int64
	CreatedAt pgtype.Timestamptz
}
