// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package pg

import (
	"context"
)

const addComplaint = `-- name: AddComplaint :exec
INSERT INTO complaints(user_id, book_id, text)
VALUES ($1, $2, $3)
`

type AddComplaintParams struct {
	UserID int64
	BookID int64
	Text   string
}

func (q *Queries) AddComplaint(ctx context.Context, arg AddComplaintParams) error {
	_, err := q.db.Exec(ctx, addComplaint, arg.UserID, arg.BookID, arg.Text)
	return err
}

const addFavoriteBook = `-- name: AddFavoriteBook :exec
INSERT INTO user_favorite_books (user_id, book_id)
VALUES ($1, $2)
ON CONFLICT (user_id, book_id) DO NOTHING
`

type AddFavoriteBookParams struct {
	UserID int64
	BookID int64
}

func (q *Queries) AddFavoriteBook(ctx context.Context, arg AddFavoriteBookParams) error {
	_, err := q.db.Exec(ctx, addFavoriteBook, arg.UserID, arg.BookID)
	return err
}

const getCommentsByBookId = `-- name: GetCommentsByBookId :many
SELECT id, user_id, book_id, text, created_at
FROM comments_books
WHERE book_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetCommentsByBookIdParams struct {
	BookID int64
	Limit  int32
	Offset int32
}

func (q *Queries) GetCommentsByBookId(ctx context.Context, arg GetCommentsByBookIdParams) ([]CommentsBook, error) {
	rows, err := q.db.Query(ctx, getCommentsByBookId, arg.BookID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CommentsBook
	for rows.Next() {
		var i CommentsBook
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BookID,
			&i.Text,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCommentsByUserId = `-- name: GetCommentsByUserId :many
SELECT id, user_id, book_id, text, created_at
FROM comments_books
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetCommentsByUserIdParams struct {
	UserID int64
	Limit  int32
	Offset int32
}

func (q *Queries) GetCommentsByUserId(ctx context.Context, arg GetCommentsByUserIdParams) ([]CommentsBook, error) {
	rows, err := q.db.Query(ctx, getCommentsByUserId, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CommentsBook
	for rows.Next() {
		var i CommentsBook
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BookID,
			&i.Text,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getComplaints = `-- name: GetComplaints :many
SELECT id, user_id, book_id, text, created_at
FROM complaints
`

func (q *Queries) GetComplaints(ctx context.Context) ([]Complaint, error) {
	rows, err := q.db.Query(ctx, getComplaints)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Complaint
	for rows.Next() {
		var i Complaint
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BookID,
			&i.Text,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCountCommentsByBookId = `-- name: GetCountCommentsByBookId :one
SELECT COUNT(*)
FROM comments_books
WHERE book_id = $1
`

func (q *Queries) GetCountCommentsByBookId(ctx context.Context, bookID int64) (int64, error) {
	row := q.db.QueryRow(ctx, getCountCommentsByBookId, bookID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getCountCommentsByUserId = `-- name: GetCountCommentsByUserId :one
SELECT COUNT(*)
FROM comments_books
WHERE user_id = $1
`

func (q *Queries) GetCountCommentsByUserId(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, getCountCommentsByUserId, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getSubscribeeIDs = `-- name: GetSubscribeeIDs :many
SELECT subscribee_id
FROM subscriptions
WHERE subscriber_id = $1
`

func (q *Queries) GetSubscribeeIDs(ctx context.Context, subscriberID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, getSubscribeeIDs, subscriberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var subscribee_id int64
		if err := rows.Scan(&subscribee_id); err != nil {
			return nil, err
		}
		items = append(items, subscribee_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubscriberIDs = `-- name: GetSubscriberIDs :many
SELECT subscriber_id
FROM subscriptions
WHERE subscribee_id = $1
`

func (q *Queries) GetSubscriberIDs(ctx context.Context, subscribeeID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, getSubscriberIDs, subscribeeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var subscriber_id int64
		if err := rows.Scan(&subscriber_id); err != nil {
			return nil, err
		}
		items = append(items, subscriber_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertComment = `-- name: InsertComment :exec
INSERT INTO comments_books (user_id, book_id, text)
VALUES ($1, $2, $3)
`

type InsertCommentParams struct {
	UserID int64
	BookID int64
	Text   string
}

func (q *Queries) InsertComment(ctx context.Context, arg InsertCommentParams) error {
	_, err := q.db.Exec(ctx, insertComment, arg.UserID, arg.BookID, arg.Text)
	return err
}

const listFavoriteBooks = `-- name: ListFavoriteBooks :many
SELECT book_id
FROM user_favorite_books
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListFavoriteBooks(ctx context.Context, userID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, listFavoriteBooks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var book_id int64
		if err := rows.Scan(&book_id); err != nil {
			return nil, err
		}
		items = append(items, book_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeFavoriteBook = `-- name: RemoveFavoriteBook :exec
DELETE FROM user_favorite_books
WHERE user_id = $1 AND book_id = $2
`

type RemoveFavoriteBookParams struct {
	UserID int64
	BookID int64
}

func (q *Queries) RemoveFavoriteBook(ctx context.Context, arg RemoveFavoriteBookParams) error {
	_, err := q.db.Exec(ctx, removeFavoriteBook, arg.UserID, arg.BookID)
	return err
}

const subscribe = `-- name: Subscribe :exec
INSERT INTO subscriptions (subscriber_id, subscribee_id)
VALUES ($1, $2)
`

type SubscribeParams struct {
	SubscriberID int64
	SubscribeeID int64
}

func (q *Queries) Subscribe(ctx context.Context, arg SubscribeParams) error {
	_, err := q.db.Exec(ctx, subscribe, arg.SubscriberID, arg.SubscribeeID)
	return err
}
